//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Company_SDEntities1 : DbContext
    {
        public Company_SDEntities1()
            : base("name=Company_SDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    
        [DbFunction("Company_SDEntities1", "getDataDepartment")]
        public virtual IQueryable<getDataDepartment_Result> getDataDepartment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getDataDepartment_Result>("[Company_SDEntities1].[getDataDepartment]()");
        }
    }
}
