//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string Pname { get; set; }
        public int Pnumber { get; set; }
        public string Plocation { get; set; }
        public string City { get; set; }
        public Nullable<int> Dnum { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
